Water Heater. Ability to send only mandatory parameters
Andre0512/pyhOn pull request #14
Opened 2023-07-11 14:23 UTC by VadymMelnychuk

In my case I have command StartProgram that has 3 parameters ([Commands TestData Link](https://github.com/Andre0512/hon-test-data/blob/12a40ce2dc918e6d21bc1248ba917ad92826f018/test_data/wh_265/commands.json#L114)):
- onOffStatus
- machMode
- tempSel
But only `onOffStatus` is mandatory. 
The problem is when I send `StartProgram` command the body contains all 3 parameters with default values. As result I set `tempSel` to default value. Instead of this I want to send only mandatory parameters.
I'm also preparing changes Hon repository as well

2023-07-11 16:01 UTC, Andre0512 commented
Looks good so far, thanks!
You can also use black locally to format the code 🙂 
```pip install black; black pyhon/```

2023-07-12 08:46 UTC, VadymMelnychuk commented
Thanks for help me with black :)
Now it's fixed

2023-07-13 16:37 UTC, VadymMelnychuk commented
@Andre0512 
I added more options to manage the process of sending command

2023-07-13 22:52 UTC, Andre0512 commented
Good work, I think this can also resolve the new issue https://github.com/Andre0512/hon/issues/92 :slightly_smiling_face: 
To get the actions running, have a look at the [python-check.yml](https://github.com/Andre0512/pyhOn/blob/main/.github/workflows/python-check.yml). You can test the action local if you run:
```bash
pip install -r requirements_dev.txt
flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
mypy pyhon/
pylint  $(git ls-files '*.py')
black . --check```

2023-07-16 00:38 UTC, Andre0512 requested changes

2023-07-17 07:03 UTC, VadymMelnychuk commented on pyhon/commands.py
> +    async def send(self, onlyMandatory: bool = False) -> bool:
Done

2023-07-18 19:25 UTC, Andre0512 approved these changes

2023-07-18 19:26 UTC, merged

2023-07-18 19:37 UTC, Andre0512 commented
Thanks! It's now available in the new version `v0.15.0` :slightly_smiling_face: